// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADhgM0YXUwN3AF4856B84A9SxRPHDBYCU',
    appId: '1:769474711801:web:844b50543c0a0214265228',
    messagingSenderId: '769474711801',
    projectId: 'mental-health-support-a7af7',
    authDomain: 'mental-health-support-a7af7.firebaseapp.com',
    storageBucket: 'mental-health-support-a7af7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO4xuN90xBFq0eufLmtsaZmrEsQ6Ejmgg',
    appId: '1:769474711801:android:3b18b1f057c55ab7265228',
    messagingSenderId: '769474711801',
    projectId: 'mental-health-support-a7af7',
    storageBucket: 'mental-health-support-a7af7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzg5ZGv0lVr03SeK_2AfyPmam7tJzy8m4',
    appId: '1:769474711801:ios:06400a07c6f06046265228',
    messagingSenderId: '769474711801',
    projectId: 'mental-health-support-a7af7',
    storageBucket: 'mental-health-support-a7af7.appspot.com',
    iosBundleId: 'com.example.mentalHealthSupport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzg5ZGv0lVr03SeK_2AfyPmam7tJzy8m4',
    appId: '1:769474711801:ios:06400a07c6f06046265228',
    messagingSenderId: '769474711801',
    projectId: 'mental-health-support-a7af7',
    storageBucket: 'mental-health-support-a7af7.appspot.com',
    iosBundleId: 'com.example.mentalHealthSupport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADhgM0YXUwN3AF4856B84A9SxRPHDBYCU',
    appId: '1:769474711801:web:e90c0af9ae815299265228',
    messagingSenderId: '769474711801',
    projectId: 'mental-health-support-a7af7',
    authDomain: 'mental-health-support-a7af7.firebaseapp.com',
    storageBucket: 'mental-health-support-a7af7.appspot.com',
  );

}